//! Generated by scripts/extensions.mjs from the contents of extensions/.
//! Do not edit: run `pnpm extensions` instead. The committed copy is the one
//! for an empty folder.

/// The id of every extension compiled in.
pub const EXTENSIONS: &[&str] = &[];

/// Adds every extension's Tauri plugin to the app.
pub fn register<R: tauri::Runtime>(builder: tauri::Builder<R>) -> tauri::Builder<R> {
    builder
}
